name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jre

      - uses: actions/checkout@v1

      - name: Set up credentials
        run: |
          echo 'Global / credentials += ' > credentials.sbt
          echo 'Credentials("GitHub Package Registry", "maven.pkg.github.com", "lavrov", "${{ secrets.GITHUB_TOKEN }}")' >> credentials.sbt

      - name: Build
        run: make prepare-gh-pages

      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          external_repository: TorrentDam/TorrentDam.github.io
          publish_branch: gh-pages
          publish_dir: target/gh-pages
